### ISSUE TITLE
M73 progress bar doesn't go to 100%

### ISSUE THREAD

**Issue by a1b0hph0b1a** [tpmullan/OctoPrint-DetailedProgress#12]
When the M73 messages are enabled, the progress bar doesn't go all the way to 100%, it stops at about 95% when the print is done.

**Comment by tpmullan** [comment]
I don't think the code it is using to send status updates is triggered at 100%  I can look into modifying the code, but this will be low priority.  Feel free to submit a pull request.

**Comment by a1b0hph0b1a** [comment]
No rush. Just thought I'd mention in case you didn't know. I'm in no rush, can use the old M73 plugin in mean time.

**Comment by tpmullan** [comment]
I added some code, but still need to test it a little more.  You can install it manually from the install plugin page with the link https://github.com/tpmullan/OctoPrint-DetailedProgress/archive/feature/update-0.2.5.zip
