### ISSUE TITLE
Is not compatible with the BigtreeTech TFT35 v3.0 touchscreen

### ISSUE THREAD

**Issue by Silversunbeam** [tpmullan/OctoPrint-DetailedProgress#18]
Unless marlin mode is selected, no progress information is displayed on screen.

**Comment by fangedhex** [comment]
I saw on reddit and other sites that you need to use UART pins connected to raspberry pi GPIO for it to work. I did NOT tested that myself : I'm waiting my BTT TFT35 E3 v3.0 to test out.

**Comment by StarNamer** [comment]
This is due to Marlin not sending notifications to the secondary host (the TFT35). I've submitted a pull request for a fix.

**Comment by tpmullan** [comment]
I am marking this as closed since it seems unrelated.  If that assumption is incorrect please let me know.
