### ISSUE TITLE
can not handle delta-printers ?

### ISSUE THREAD

**Issue by mameniac** [tpmullan/OctoPrint-DetailedProgress#27]
I'm using this on my Ender3 and its working fine, but on my Delta printer it always say "Bad accuracy" and showing print times wich are way off that, what the printer really need. Printer is running latest smoothieware, that maybe cause the problem ?

**Comment by Bougakov** [comment]
I have a similar issue. The root cause is that the printing speed for layer 1 is much slower than the rest, so initially, the forecast is too pessimistic (days), then it gets back on track.

So it would be a good idea to discard the 1st layer from the calculations.

**Comment by tpmullan** [comment]
This plugin just displays the estimate and does not have anything to do with generating the value.  I had the same issue with my Ender 3 pro. I would suggest using https://plugins.octoprint.org/plugins/PrintTimeGenius/ to get better estimates.
