### ISSUE TITLE
What does Good and  Bad accuracy mean?

### ISSUE THREAD

**Issue by alambert0008** [tpmullan/OctoPrint-DetailedProgress#30]
Hi Tom - Sorry for posting here.. I did not see another way to contact you.   Love the plugin, but have a question. What does Good and  Bad accuracy mean?

**Comment by tpmullan** [comment]
It is just a metric showing how confident the algorithm is in the estimate of time remaining that you are seeing.  In practice this means if it says the accuracy is poor and there are 2 hours left your print might be 1 hour or 3 hours.  I would suggest using https://plugins.octoprint.org/plugins/PrintTimeGenius/ to get better estimates.
