### ISSUE TITLE
Progress showing only a fraction of actual progress

### ISSUE THREAD

**Issue by bthaler1** [tpmullan/OctoPrint-DetailedProgress#33]
I left some comments on this closed issue, but there's been no response so I'm opening a new issue:
https://github.com/tpmullan/OctoPrint-DetailedProgress/issues/11

Progress on the LCD is showing only a fraction of the real progress according to Octoprint. It seems to happen whether it's a long print or a short one. The progress does eventually correct itself as the print progresses eventually showing 100% as the print finishes.

I am running Octoprint 1.5.3 and printer is an Ender 3 Pro running Marlin bugfix-2.0.x (Feb 3 2021).

**Comment by tpmullan** [comment]
So the way this works is it will periodically update.  The number is not going to be the exact same as the web.  It should be similar and update as the print goes.  From your post on the closed issue it sounds like it was updating with the print and following similar to the web interface.  Unless you have more info I do not see an error that can be corrected.  If you want to try and fix it you can submit a PR
