### ISSUE TITLE
compatible longer  lk4 pro ?

### ISSUE THREAD

**Issue by loroff** [tpmullan/OctoPrint-DetailedProgress#47]
bonjours ce plug in est t il compatible avec l ecran d une lk 4 pro car malgré l installation je n ai aucune indication qui s affiche a  l ecran merci 
![1670577055325](https://user-images.githubusercontent.com/98763825/206666475-d6b160f5-652a-455a-b852-701e9ffae6d2.jpg)

**Comment by tpmullan** [comment]
Cela ressemble beaucoup à ce problème: https://github.com/tpmullan/OctoPrint-DetailedProgress/issues/46
Je suggérerais de compiler votre propre firmware et de vous assurer que la prise en charge des messages est activée. Sinon, il semble que votre imprimante ne soit pas prise en charge.
