### ISSUE TITLE
Percentage shown "12.96omplete" not "12% complete" or "12.69% complete"

### ISSUE THREAD

**Issue by tehniq3** [tpmullan/OctoPrint-DetailedProgress#48]
On ANET A8 LCD 2004 display shown with your plugin:
![afisare_12_69omplete](https://user-images.githubusercontent.com/4947574/229307464-8aae24bc-1591-4b77-859c-89ef8c8d5d61.jpg)
but other info are ok, "Good accuracy", "ETL 00h25m56s", "ETA 3/3 9.44PM"

without your plugin, last rowis empty
![afisare_cuOctoprint](https://user-images.githubusercontent.com/4947574/229307506-d59c22f4-56c6-4f41-a997-9c733661ab09.jpg)

original, without Octoprint:
![afisare_faraOctoprint](https://user-images.githubusercontent.com/4947574/229307524-28395ffb-d50c-4c1e-a9f0-b4a52d2fa4c8.jpg)

I try it a lot of version of text istead "{completion:.2f}% complete", adding spaces or change the text.. no good results...

**Comment by tehniq3** [comment]
solved !!! solution is I found at https://github.com/eyal0/OctoPrint-PrintTimeGenius/issues/302 😁

you are right ! instead one % I put %%% 😎 I need to change in {completion:.2f}%%% done to see "16.4% done"
![rezultat_bun_niq_ro_Anet_A8](https://user-images.githubusercontent.com/4947574/229372954-82aae827-757d-4399-a267-ab2fb7cea91d.jpg)
PS: many thank to **eyal** ( https://github.com/eyal0 )

**Comment by tpmullan** [comment]
That is interesting. I guess the screen is thinking the % character is a command or something. If you want to create a PR and add info to the readme so others can easily fix this I can merge it.
