### ISSUE TITLE
all_messages

### ISSUE THREAD

**Issue by jfrancais** [tpmullan/OctoPrint-DetailedProgress#7]
Having some strangemess where by changing my messages and removing existing don't usually stick or sometimes appear twice upon save.  I looked at the config.yaml file and saw an all_messages setting in detailedprogress which doesn't show in the documentation.  My settings appear there but the messages contains values I didnt set.

**Comment by tpmullan** [comment]
I am going to close this and track it under #8 since it looks like the same issue
